### ISSUE TITLE
Real world example for set-finder-icon

### ISSUE THREAD

**Issue by welby12** [pingortle/dotfiles#1]
Sorry, I'm not that great with AppleScript. Would it be possible for you to show me an example of how to use an image (~/Desktop/image.png) and change the icon of an app (/Applications/Google Chrome.app)?

**Comment by kjlape** [comment]
@welby12 Sure! The `set-finder-icon` script is designed to run as a CLI. Here's a quick overview:

1. Open Terminal.app
1. Type `set-finder-icon "path/to/my/image.png" "/Applications/Google Chrome.app"`
1. Go to `/Applications` in Finder. Google Chrome.app should have the icon you set.
1. Bonus: If you quit Chrome and restart it, it _should_ show the new icon in the Dock as well.

I must admit this is not a script I use a lot, but it was fun to put it together. 😂 May I ask what you what you're trying to accomplish with it? I might be able to zero in on your issue with more info.

**Comment by welby12** [comment]
I have a custom icon I made for Google Chrome, and whenever it updates the icon is wiped. That way I could make this script run at login. Same thing happens to Slack I believe. Will give this a try, thanks!

**Comment by kjlape** [comment]
Awesome! Glad you found this useful. 👍
